// <auto-generated />
using System;
using ApiBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiBackend.Models.Contagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CultoId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantidadeCadeirasA")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeCadeirasB")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeCadeirasC")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeCadeirasD")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeExterno")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeGaleria")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeOnline")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadePulpito")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeSalas")
                        .HasColumnType("integer");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CultoId");

                    b.ToTable("Contagens");
                });

            modelBuilder.Entity("ApiBackend.Models.Culto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("GrupoRecepcao")
                        .HasColumnType("integer");

                    b.Property<string>("LiderRecepcao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Turno")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cultos");
                });

            modelBuilder.Entity("ApiBackend.Models.Contagem", b =>
                {
                    b.HasOne("ApiBackend.Models.Culto", null)
                        .WithMany("Contagens")
                        .HasForeignKey("CultoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiBackend.Models.Culto", b =>
                {
                    b.Navigation("Contagens");
                });
#pragma warning restore 612, 618
        }
    }
}
