// <auto-generated />
using System;
using ApiBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiBackend.Models.Contagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CultoId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantidadeCadeirasA")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeCadeirasB")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeCadeirasC")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeCadeirasD")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeExterno")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("externo");

                    b.Property<int>("QuantidadeGaleria")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("galeria");

                    b.Property<int>("QuantidadeOnline")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("online");

                    b.Property<int>("QuantidadePulpito")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("pulpito");

                    b.Property<int>("QuantidadeSalas")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("salas");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("total");

                    b.HasKey("Id");

                    b.HasIndex("CultoId")
                        .IsUnique();

                    b.ToTable("Contagens");

                    b.HasAnnotation("Relational:JsonPropertyName", "contagens");
                });

            modelBuilder.Entity("ApiBackend.Models.Culto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasJsonPropertyName("data");

                    b.Property<int>("GrupoRecepcao")
                        .HasColumnType("integer");

                    b.Property<string>("LiderRecepcao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("lider_recepcao");

                    b.Property<DateTime>("Registro")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("registro");

                    b.Property<int>("Turno")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cultos");
                });

            modelBuilder.Entity("ApiBackend.Models.Contagem", b =>
                {
                    b.HasOne("ApiBackend.Models.Culto", null)
                        .WithOne("Contagens")
                        .HasForeignKey("ApiBackend.Models.Contagem", "CultoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiBackend.Models.Culto", b =>
                {
                    b.Navigation("Contagens");
                });
#pragma warning restore 612, 618
        }
    }
}
